baseURL = 'https://example.org/'
locale = 'en-us'
title = 'JavaScript Code Recipes'
theme = 'ananke'

[markup]
  [markup.highlight]
    style = 'solarized-light'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
