baseURL = 'https://example.org/'
locale = 'en-us'
title = 'JavaScript Code Recipes'
theme = 'ananke'

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  custom_css = ["code-fence-border.css"]
